### ISSUE TITLE
[Doc Fix]: Fixing Content Interactions

### ISSUE THREAD

**Issue by carmendetroit** [bounswe/bounswe2024group3#93]
### Issue Type

Bug Report

### Issue Description

Please detect and fix the problems below that were pointed by the feedbacks and clearly document what you changed. You are highly encouraged to take a look at the feedbacks on discord and take all the other considerations while you are solving your issue.

## Content Interaction

Which content can users bookmark ?

**Content** is defined as information posted by users, but in your scenario 2, Tuğçe bookmarks a page.

By the way, who does create book pages ?

> 3.2 Users can bookmark content for future reference.

You should avoid explaining why if it is not necessary.

> 3.3 Users can like or dislike posts in order to voice their feelings.

##

**Comment by burkaykinik** [comment]
- I removed the "in order to voice their feelings" phrase from the User Requirements 3.3, because it unnecesarily explains why that requirement exists.
- I changed "content" with "book page" in User requirement 3.2, since it is a clearer explanation of the requirement.
@carmendetroit can you look over my changes and close the issue if you are satisfied please.

**Comment by carmendetroit** [comment]
Thank you for your effort!
